### ISSUE TITLE
Logger Name

### ISSUE THREAD

**Issue by ccoffrin** [lanl-ansi/PowerModelsSecurityConstrained.jl#17]
Seem of the logger printing name can be shortened to `PMSC`.

**Comment by ccoffrin** [comment]
@rofinn, a quick question on Memento.  

In this package `PowerModelsSecurityConstrained`, internally I would like the logger id to be the name of the package i.e. `const LOGGER = Memento.getlogger(@__MODULE__)` however, by default when printing to the terminal I would like to abbreviate it, so it looks like `[info | PMSC]: ...` instead of `[info | PowerModelsSecurityConstrained]: ...` is there an easy way to do that?

**Comment by rofinn** [comment]
Interesting, it isn't part of the public API, but you should be able to do something like:

```
const LOGGER = Memento.getlogger(@__MODULE__)

function __init__()
   LOGGER.name = "PMSC"
   Memento.register(LOGGER)
end
```

This would make it so that your `Memento.getlogger(...)` calls would work the same way, but the internal logger name that's passed to the record type is just `PMSC`.

Example)

```
julia> module MyPkg

       using Memento

       const LOGGER = getlogger(@__MODULE__)

       function __init__()
           LOGGER.name = "MyPkg2"
           Memento.register(LOGGER)
       end

       function foo()
           info(LOGGER, "Hello World!")
       end

       end
Main.MyPkg

julia> MyPkg.foo()
[info | MyPkg2]: Hello World!
```

**Comment by ccoffrin** [comment]
Thanks @rofinn.  Your proposed change does appear to work well inside the package but I ran into two issues from outside the package,
```
using Memento, PowerModelsSecurityConstrained
Memento.setlevel!(Memento.getlogger(PowerModelsSecurityConstrained), "error")
```
Does not appear to change the output level.

```
using Memento, PowerModelsSecurityConstrained
const LOGGER = Memento.getlogger(PowerModelsSecurityConstrained)
info(LOGGER, "hello")
```
Package internal messages print as `[info | PMSC]` while external messages print as `[info | PowerModelsSecurityConstrained]`. 

So for now I am thinking that I will stick with `PowerModelsSecurityConstrained` for consistency.

**Comment by rofinn** [comment]
Oops, yeah, my bad. The order of registering vs changing the name matters when used externally. What you actually want then is to register the logger using the current name and then change the name property after that. The reason you're seeing that behaviour is because it's getting registered as `"PMSC"`, so when you do `getlogger(PowerModelsSecurityConstrained)` it isn't seeing that logger and returning a new empty logger (wonder if I should change that behaviour?).

Above suggestion:
```
_LOGGER.name = "PMSC" # take note of discussion in issue #17
Memento.register(_LOGGER)
```

```
julia> using PowerModelsSecurityConstrained
[ Info: Recompiling stale cache file /Users/rory/.julia/compiled/v1.0/PowerModelsSecurityConstrained/JKJjJ.ji for PowerModelsSecurityConstrained [53333297-f92c-5019-980b-942fc744b407]

julia> using Memento

julia> Memento._loggers
Dict{AbstractString,Logger} with 5 entries:
  "root"                 => Logger(root)
  "InfrastructureModels" => Logger(InfrastructureModels)
  "PowerModels"          => Logger(PowerModels)
  "Memento"              => Logger(Memento)
  "PMSC"                 => Logger(PMSC)
```

The loggers dict doesn't have a logger with your package name.

Rearranging the order to:

```
Memento.register(_LOGGER)
_LOGGER.name = "PMSC" # take note of discussion in issue #17
```

```
julia> using PowerModelsSecurityConstrained
[ Info: Recompiling stale cache file /Users/rory/.julia/compiled/v1.0/PowerModelsSecurityConstrained/JKJjJ.ji for PowerModelsSecurityConstrained [53333297-f92c-5019-980b-942fc744b407]

julia> using Memento

julia> Memento._loggers
Dict{AbstractString,Logger} with 5 entries:
  "root"                           => Logger(root)
  "InfrastructureModels"           => Logger(InfrastructureModels)
  "PowerModels"                    => Logger(PowerModels)
  "PowerModelsSecurityConstrained" => Logger(PMSC)
  "Memento"                        => Logger(Memento)

julia> Memento.setlevel!(Memento.getlogger(PowerModelsSecurityConstrained), "error")

julia> info(getlogger(PowerModelsSecurityConstrained), "Hello World!")

julia> error(getlogger(PowerModelsSecurityConstrained), "Goodbye World!")
[error | PMSC]: Goodbye World!
ERROR: Goodbye World!
Stacktrace:
 [1] error(::Logger, ::String) at /Users/rory/.julia/packages/Memento/UgJr2/src/loggers.jl:429
 [2] top-level scope at none:0
```

Sorry, this isn't a behaviour I initially had in mind. Looks like it's still a one line change though :)

**Comment by ccoffrin** [comment]
That works great.  Thanks!
