### ISSUE TITLE
Reversing transformer orientation

### ISSUE THREAD

**Issue by opfsolver** [lanl-ansi/PowerModelsSecurityConstrained.jl#39]
The goc2 data loading code performs a check whether the transformer orientation needs to be reversed:

https://github.com/lanl-ansi/PowerModelsSecurityConstrained.jl/blob/1d72c2caab6d31230e8d663be5afc97fe6fbfd51/src/io/goc_c2.jl#L416-L431

My questions are:
- Why is this necessary?
- When using the GOC3 competition data, do we need to check whether we need to add this transformation (it doesn't appear so)?

Please feel free to ignore below, it's just showing my reasoning for what I thought may have been possible causes:
1) There could be a discrepancy between `raw` and `json` formats: not the case, because of the way `branch_id` is built when [merging the json data](https://github.com/lanl-ansi/PowerModelsSecurityConstrained.jl/blob/1d72c2caab6d31230e8d663be5afc97fe6fbfd51/src/io/goc_c2.jl#L171)
2) There could be some ambiguities/strangeness when parsing transformer data from raw: also not the case
- 2-winding transformers have no issues
- 3-winding transformers are a little bit complicated, but end up creating an extra bus (star bus) and decomposing a single 3-winding transformer into three 2-winding transformers. There all the `t_bus` values are the star bus id, so the condition `branch["source_id"][2] == branch["t_bus"]` is also not satisfied as `["source_id"][2]` is never star id, but is one of the original three bus ids.

**Comment by ccoffrin** [comment]
> Why is this necessary?

By default PowerModels sets the orientation of all parallel branches (including transformers) to be the same (and will re-orient them as needed). This is important when defining some types of convex relaxations of the AC OPF.

The GOC C2 competition benchmark solver used a heuristic for setting tap ratios on transformers, which did not work correctly after the PowerModels default orientation change was applied parallel transformers with different orientations. This code un-does the default PowerModels transformation so that the tap setting heuristic will work as expected.

Parallel transformers with different orientations most likely are indicative of a data entry error, but a robust software should be able handle them.

> When using the GOC3 competition data, do we need to check whether we need to add this transformation (it doesn't appear so)?

GOC C3 is out of scope of this repo. All questions regarding that should be directed to the competition organizers, https://gocompetition.energy.gov/contact-us

**Comment by opfsolver** [comment]
Thanks for the quick reply!

IIUC, the ordering of what happens in `code1` is:
1) **Correct parallel branch orientation in PowerModels.** Call `parse_c2_files`, which calls `_PM.parse_file` on network (`raw`) data, which calls `parse_psse`, which eventually calls `_correct_branch_directions!`, the PowerModels.jl orientation change that aligns the orientation of all parallel lines. This changes `t_bus` and `f_bus`, the variables that PowerModels uses when building the JuMP model, but keeps `source_id` intact.
2) **Reverse the parallel orientation correction.** Call `build_c2_pm_model`, which does the reversal of the `t_bus` and `f_bus` variables.
https://github.com/lanl-ansi/PowerModelsSecurityConstrained.jl/blob/1d72c2caab6d31230e8d663be5afc97fe6fbfd51/src/io/goc_c2.jl#L416-L431 
3) **Set the tap heuristic of the solution (closest discrete value).**
4) **Solve the ACOPF problem.** Call `run_c2_opf_soft`, which builds the JuMP model, and calls the solver.

Question 1: Does this ordering mean that in cases where correction was reversed, PowerModels might see "incorrect" parallel branch orientations? I assume this would mean that some convex relaxations are not as good (or maybe can't be used at all?), but the solution is still correct when using arbitrary orientations.

My reconstruction of your decision making process when designing the software:
- The reason the heuristic did not work correctly is that `1/tap` is a nonlinear transformation, meaning that discrete steps are no longer evenly distributed in the `1/tap` space [1].
- So the choice was between doing what was done, or the alternative, which is using the same heuristic in the `1/tap` space, by transforming the steps as well. That was considered too much faff (no judgement, would have done the same!) and since the solution is still correct, we are just taking a small performance hit by not optimising for the relaxations.

Question 2: Is the above roughly correct?

[1] The same is not true for `shift` (just a - sign), which potentially means the heuristic could be used with reversed orientation?

**Comment by ccoffrin** [comment]
> Question 1

Yes, but this should only be a potential performance issue and not a correctness issue. For the purpose of this repo the non-convex AC solver was the primary use case and in that formulation there is no impact from mixed branch orientations.

> Question 2

Your reconstruction of the decision process is correct.  This code did not consider optimization of the `shift` parameter, as I recall, so this aspect was ignored.

**Comment by opfsolver** [comment]
Awesome, thanks for the quick response!
